# Welcome to Jekyll!

# Website settings
title: Ming Huang
description: Ming's perosonal website,use Jekyll and github pages.
keywords: Ming,Jekyll,github,gh-pages

img_path: /static/assets/img/blog 

# author -- index page "about me" section
author:  
  name: Ming Huang  
  first_name: Ming  
  last_name: Huang  
  avatar: /static/assets/img/landing/avatar.jpg  .
  github_username: mingh2  
  linkedin_id: ming-huang-6329b0117
  #facebook_username:   
  #twitter_username:  
  email: mingh2@uci.edu  # Leave blank if you don't have now
  #cv:   # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-java-bold
    - name: icon-python
  skill_icon2:
    - name: icon-shell
    - name: icon-mobile-device
  desc: |
    Currently a senior student from the University of California, Irvine, I am studying Computer Science and specializing in both 
    Information and Artificial Intelligence. For now, my main interest is artificial intelligence but I have also done researches 
    and projects related to databases and mobile application. This website will tell you everything about me!  
  # Describe yourself.

# comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  # name: 
  # public_key: 

# analytics
## google analytics
# ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
# go:
  # id:

## growingIO
# gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

# donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
